### ISSUE TITLE
Error loading plugin in QGIS master

### ISSUE THREAD

**Issue by elpaso** [sourcepole/pgversion#18]
After loading the plugin from plugin manager:

```
Couldn't load plugin 'pgversion' due to an error when calling its classFactory() method 

ValueError: PyCapsule_GetPointer called with incorrect name 
Traceback (most recent call last):
  File "/home/ale/dev/QGIS/build-local-qt5152-release_gdal3/output/python/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pgversion/__init__.py", line 23, in classFactory
    from .pgVersion import PgVersion
  File "/home/ale/dev/QGIS/build-local-qt5152-release_gdal3/output/python/qgis/utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pgversion/pgVersion.py", line 30, in 
    from .forms.help import HelpDialog
  File "/home/ale/dev/QGIS/build-local-qt5152-release_gdal3/output/python/qgis/utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pgversion/forms/help.py", line 28, in 
    FORM_CLASS, _ = uic.loadUiType(os.path.join(
  File "/home/ale/dev/QGIS/build-local-qt5152-release_gdal3/output/python/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/home/ale/local5_15_2_release_gdal3/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 21, in 
  File "/home/ale/dev/QGIS/build-local-qt5152-release_gdal3/output/python/qgis/utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ValueError: PyCapsule_GetPointer called with incorrect name


Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0] 
QGIS version: 3.17.0-Master Master, 52e8c5bf2e 
```

**Comment by hdus** [comment]
Unfortunately, I cannot reproduce the error. With my current QGIS 3.18 version under Ubuntu 20.04 the plugin works fine.

**Comment by hdus** [comment]
Does this issue still persists?

**Comment by HusseinKabbout** [comment]
Closing this issue because of no inactivity. Feel free to reopen this issue if the problem still persists.
