### ISSUE TITLE
Error when trying to prepare a Layer for versioning or load versioned layers

### ISSUE THREAD

**Issue by useher** [sourcepole/pgversion#9]
When i try to prepare a layer in QQIS or when i try to load a versioned Layer i get the following errormessage;
```
Traceback (most recent call last):
  File "/home/useher/.qgis2/python/plugins/pgversion/forms/Ui_pgLoadVersion.py", line 123, in on_cmbServer_currentIndexChanged
    self.initDB(p0)
  File "/home/useher/.qgis2/python/plugins/pgversion/forms/Ui_pgLoadVersion.py", line 79, in initDB
    if not self.tools.check_PGVS_revision(myDb):
  File "/home/useher/.qgis2/python/plugins/pgversion/pgVersionTools.py", line 427, in check_PGVS_revision
    db_major_revision = result["PGVSREVISION"][0].split('.')[1]
IndexError: list index out of range
```
When i prepare it in postgres with the same user and load the Layer via dbmanagerthe other functions work.

The version is 2.1.35, pg-version is 9.6.x, QGIS is 2.18.16

**Comment by useher** [comment]
Seems, that the function versions.pgvsrevision() returns a wrong text. This version seems to work right:

> CREATE OR REPLACE FUNCTION versions.pgvsrevision()
>   RETURNS text AS
> $BODY$
> DECLARE
> revision TEXT;
> BEGIN	
>   --revision := '218';
>   revision := '2.1.8';
>  RETURN revision ;                             
>   END;
> $BODY$
>   LANGUAGE plpgsql VOLATILE
>   COST 100;
